# Generated by Django 6.0 on 2026-01-09 06:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('policies', '0002_alter_policy_job_cd_alter_policy_school_cd'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('birth_year', models.IntegerField(blank=True, null=True, verbose_name='출생년도')),
                ('district', models.CharField(blank=True, max_length=20, verbose_name='거주 구')),
                ('income_level', models.CharField(blank=True, choices=[('below_50', '기준중위소득 50% 이하'), ('below_100', '기준중위소득 100% 이하'), ('above_100', '기준중위소득 100% 초과'), ('unknown', '모름')], max_length=20, verbose_name='소득수준')),
                ('job_status', models.CharField(blank=True, choices=[('employed', '재직중'), ('unemployed', '미취업'), ('job_seeking', '구직중'), ('student', '학생'), ('startup', '창업준비'), ('freelancer', '프리랜서'), ('other', '기타')], max_length=20, verbose_name='취업상태')),
                ('education_status', models.CharField(blank=True, choices=[('enrolled', '재학'), ('on_leave', '휴학'), ('graduated', '졸업'), ('dropout', '중퇴'), ('other', '기타')], max_length=20, verbose_name='학력상태')),
                ('marriage_status', models.CharField(blank=True, choices=[('single', '미혼'), ('married', '기혼'), ('other', '기타')], max_length=20, verbose_name='혼인상태')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('interests', models.ManyToManyField(blank=True, related_name='interested_profiles', to='policies.category')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'profile',
            },
        ),
    ]
