# Generated by Django 6.0 on 2026-01-13 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_scrap'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='children_ages',
            field=models.JSONField(blank=True, default=list, help_text='자녀 나이 리스트 (예: [5, 8])', verbose_name='자녀 나이'),
        ),
        migrations.AddField(
            model_name='profile',
            name='has_children',
            field=models.BooleanField(default=False, verbose_name='자녀 유무'),
        ),
        migrations.AddField(
            model_name='profile',
            name='household_size',
            field=models.IntegerField(blank=True, help_text='본인 포함 가구원 수', null=True, verbose_name='가구원 수'),
        ),
        migrations.AddField(
            model_name='profile',
            name='housing_type',
            field=models.CharField(blank=True, choices=[('jeonse', '전세'), ('monthly', '월세'), ('owned', '자가'), ('gosiwon', '고시원'), ('parents', '부모님집'), ('public', '공공임대'), ('other', '기타')], max_length=20, verbose_name='주거형태'),
        ),
        migrations.AddField(
            model_name='profile',
            name='income_amount',
            field=models.IntegerField(blank=True, help_text='월 평균 소득 (만원 단위)', null=True, verbose_name='월 소득(만원)'),
        ),
        migrations.AddField(
            model_name='profile',
            name='needs',
            field=models.JSONField(blank=True, default=list, help_text='필요한 지원 분야 리스트 (예: ["주거", "일자리"])', verbose_name='필요분야'),
        ),
        migrations.AddField(
            model_name='profile',
            name='special_conditions',
            field=models.JSONField(blank=True, default=list, help_text='해당하는 특수조건 리스트 (예: ["신혼", "장애"])', verbose_name='특수조건'),
        ),
    ]
