# Generated by Django 6.0.1 on 2026-02-01 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_profile_children_ages_profile_has_children_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='email_notification_enabled',
            field=models.BooleanField(default=False, verbose_name='정책정보 알림 수신 동의'),
        ),
        migrations.AddField(
            model_name='profile',
            name='notification_email',
            field=models.EmailField(blank=True, help_text='정책 알림을 받을 이메일 주소', max_length=254, null=True, verbose_name='알림 수신 이메일'),
        ),
    ]
