# Generated by Django 5.2.8 on 2026-02-05 01:01
# [BRAIN4-31] CHOICES 정비 + 데이터 마이그레이션

from django.db import migrations, models


def migrate_housing_type_forward(apps, schema_editor):
    """
    [BRAIN4-31] housing_type 값 마이그레이션

    기존 7개 값 → 3개로 통합:
    - gosiwon (고시원) → monthly (월세)
    - parents (부모님집) → owned (자가)
    - public (공공임대) → monthly (월세)
    - other (기타) → '' (빈값)
    """
    Profile = apps.get_model('accounts', 'Profile')

    # 고시원 → 월세
    Profile.objects.filter(housing_type='gosiwon').update(housing_type='monthly')

    # 부모님집 → 자가
    Profile.objects.filter(housing_type='parents').update(housing_type='owned')

    # 공공임대 → 월세
    Profile.objects.filter(housing_type='public').update(housing_type='monthly')

    # 기타 → 빈값 (매칭에서 무시)
    Profile.objects.filter(housing_type='other').update(housing_type='')


def migrate_housing_type_backward(apps, schema_editor):
    """
    역방향 마이그레이션: 데이터 복원 불가능 (정보 손실)
    경고 출력만 수행
    """
    # 역방향 마이그레이션은 데이터 복원이 불가능합니다.
    # gosiwon/parents/public/other 중 어떤 값이었는지 알 수 없습니다.
    pass


def migrate_education_status_forward(apps, schema_editor):
    """
    [BRAIN4-31] education_status 값 마이그레이션

    기존 값 → 새 값으로 변환:
    - enrolled (재학) → university_enrolled (대학 재학)
    - leave (휴학) → university_leave (대학 휴학)
    - graduated (졸업) → university (대졸)
    - dropout (중퇴) → '' (빈값 - 매칭에서 무시)
    - other (기타) → '' (빈값)
    """
    Profile = apps.get_model('accounts', 'Profile')

    # 재학 → 대학 재학 (고교 재학인지 대학 재학인지 구분 불가하므로 대학으로 가정)
    Profile.objects.filter(education_status='enrolled').update(education_status='university_enrolled')

    # 휴학 → 대학 휴학
    Profile.objects.filter(education_status='leave').update(education_status='university_leave')

    # 졸업 → 대졸
    Profile.objects.filter(education_status='graduated').update(education_status='university')

    # 중퇴, 기타 → 빈값
    Profile.objects.filter(education_status='dropout').update(education_status='')
    Profile.objects.filter(education_status='other').update(education_status='')


def migrate_education_status_backward(apps, schema_editor):
    """역방향 마이그레이션: 데이터 복원 불가능"""
    pass


def migrate_job_status_forward(apps, schema_editor):
    """
    [BRAIN4-31] job_status 값 마이그레이션

    기타(other) 삭제:
    - other (기타) → '' (빈값)
    """
    Profile = apps.get_model('accounts', 'Profile')

    # 기타 → 빈값
    Profile.objects.filter(job_status='other').update(job_status='')


def migrate_job_status_backward(apps, schema_editor):
    """역방향 마이그레이션"""
    pass


def migrate_marriage_status_forward(apps, schema_editor):
    """
    [BRAIN4-31] marriage_status 값 마이그레이션

    기타(other) 삭제:
    - other (기타) → '' (빈값)
    """
    Profile = apps.get_model('accounts', 'Profile')

    # 기타 → 빈값
    Profile.objects.filter(marriage_status='other').update(marriage_status='')


def migrate_marriage_status_backward(apps, schema_editor):
    """역방향 마이그레이션"""
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_profile_email_notification_enabled_and_more'),
    ]

    operations = [
        # =====================================================================
        # [BRAIN4-31] 1단계: 데이터 마이그레이션 (기존 값 변환)
        # - CHOICES 변경 전에 데이터를 먼저 변환
        # - 순서 중요: 데이터 변환 → 스키마 변경
        # =====================================================================
        migrations.RunPython(
            migrate_housing_type_forward,
            migrate_housing_type_backward,
        ),
        migrations.RunPython(
            migrate_education_status_forward,
            migrate_education_status_backward,
        ),
        migrations.RunPython(
            migrate_job_status_forward,
            migrate_job_status_backward,
        ),
        migrations.RunPython(
            migrate_marriage_status_forward,
            migrate_marriage_status_backward,
        ),

        # =====================================================================
        # [BRAIN4-31] 2단계: 필드 CHOICES 변경
        # =====================================================================
        migrations.AlterField(
            model_name='profile',
            name='education_status',
            field=models.CharField(
                blank=True,
                choices=[
                    ('below_high_school', '고졸 미만'),
                    ('high_school_enrolled', '고교 재학'),
                    ('high_school', '고졸'),
                    ('university_enrolled', '대학 재학'),
                    ('university_leave', '대학 휴학'),
                    ('university', '대졸'),
                    ('graduate_school', '석박사'),
                ],
                max_length=20,
                verbose_name='학력상태',
            ),
        ),
        migrations.AlterField(
            model_name='profile',
            name='housing_type',
            field=models.CharField(
                blank=True,
                choices=[
                    ('jeonse', '전세'),
                    ('monthly', '월세'),
                    ('owned', '자가'),
                ],
                max_length=20,
                verbose_name='주거형태',
            ),
        ),
        migrations.AlterField(
            model_name='profile',
            name='job_status',
            field=models.CharField(
                blank=True,
                choices=[
                    ('employed', '재직중'),
                    ('self_employed', '자영업자'),
                    ('unemployed', '미취업'),
                    ('job_seeking', '구직중'),
                    ('student', '학생'),
                    ('startup', '창업준비'),
                    ('freelancer', '프리랜서'),
                ],
                max_length=20,
                verbose_name='취업상태',
            ),
        ),
        migrations.AlterField(
            model_name='profile',
            name='marriage_status',
            field=models.CharField(
                blank=True,
                choices=[
                    ('single', '미혼'),
                    ('married', '기혼'),
                ],
                max_length=20,
                verbose_name='혼인상태',
            ),
        ),
    ]
