# Generated by Django 5.2.11 on 2026-02-25 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_profile_education_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='income_amount',
            field=models.IntegerField(blank=True, help_text='연소득 (만원 단위)', null=True, verbose_name='연소득(만원)'),
        ),
    ]
