# Generated by Django 6.0.1 on 2026-02-26 06:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_profile_income_amount'),
        ('accounts', '0006_update_site_domain'),
    ]

    operations = [
    ]
