# Generated by Django 5.2.11 on 2026-02-26 07:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_profile_income_amount'),
        ('accounts', '0006_update_site_domain'),
    ]

    operations = [
    ]
