# Generated by Django 5.2.11 on 2026-03-04 07:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_merge_20260226_0638'),
        ('accounts', '0007_merge_20260226_1659'),
    ]

    operations = [
    ]
