# Generated by Django 6.0 on 2026-01-03 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, unique=True)),
            ],
            options={
                'verbose_name_plural': 'categories',
                'db_table': 'category',
            },
        ),
        migrations.CreateModel(
            name='Policy',
            fields=[
                ('plcy_no', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('plcy_nm', models.CharField(max_length=200)),
                ('plcy_expln_cn', models.TextField(blank=True)),
                ('plcy_sprt_cn', models.TextField(blank=True)),
                ('sprt_trgt_min_age', models.IntegerField(blank=True, null=True)),
                ('sprt_trgt_max_age', models.IntegerField(blank=True, null=True)),
                ('sprt_trgt_age_lmt_yn', models.CharField(blank=True, max_length=1)),
                ('earn_cnd_se_cd', models.CharField(blank=True, max_length=20)),
                ('earn_min_amt', models.IntegerField(blank=True, null=True)),
                ('earn_max_amt', models.IntegerField(blank=True, null=True)),
                ('mrg_stts_cd', models.CharField(blank=True, max_length=20)),
                ('job_cd', models.CharField(blank=True, max_length=20)),
                ('school_cd', models.CharField(blank=True, max_length=20)),
                ('aply_start_dt', models.DateField(blank=True, null=True)),
                ('aply_end_dt', models.DateField(blank=True, null=True)),
                ('plcy_aply_mthd_cn', models.TextField(blank=True)),
                ('aply_url_addr', models.CharField(blank=True, max_length=500)),
                ('district', models.CharField(blank=True, max_length=20, null=True)),
                ('frst_reg_dt', models.DateTimeField(blank=True, null=True)),
                ('last_mdfcn_dt', models.DateTimeField(blank=True, null=True)),
                ('categories', models.ManyToManyField(related_name='policies', to='policies.category')),
            ],
            options={
                'db_table': 'policy',
            },
        ),
    ]
