# Generated by Django 6.0 on 2026-01-03 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('policies', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='policy',
            name='job_cd',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='policy',
            name='school_cd',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
