# Generated by Django 6.0 on 2026-01-16 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('policies', '0002_alter_policy_job_cd_alter_policy_school_cd'),
    ]

    operations = [
        migrations.AddField(
            model_name='policy',
            name='biz_prd_bgng_ymd',
            field=models.DateField(blank=True, help_text='사업시작일 (BRAIN4-19)', null=True),
        ),
        migrations.AddField(
            model_name='policy',
            name='biz_prd_end_ymd',
            field=models.DateField(blank=True, help_text='사업종료일 (BRAIN4-19)', null=True),
        ),
    ]
