# Generated by Django 6.0.1 on 2026-01-16 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('policies', '0003_policy_biz_prd_bgng_ymd_policy_biz_prd_end_ymd'),
    ]

    operations = [
        migrations.AlterField(
            model_name='policy',
            name='biz_prd_bgng_ymd',
            field=models.DateField(blank=True, help_text='사업시작일 - 원본: bizPrdBgngYmd', null=True),
        ),
        migrations.AlterField(
            model_name='policy',
            name='biz_prd_end_ymd',
            field=models.DateField(blank=True, help_text='사업종료일 - 원본: bizPrdEndYmd', null=True),
        ),
    ]
