# Generated by Django 6.0.1 on 2026-01-17 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('policies', '0004_alter_policy_biz_prd_bgng_ymd_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='policy',
            name='is_for_disabled',
            field=models.BooleanField(default=False, help_text='장애인 전용 정책 (sbizCd: 0014005)'),
        ),
        migrations.AddField(
            model_name='policy',
            name='is_for_low_income',
            field=models.BooleanField(default=False, help_text='기초수급자 전용 정책 (sbizCd: 0014003)'),
        ),
        migrations.AddField(
            model_name='policy',
            name='is_for_newlywed',
            field=models.BooleanField(default=False, help_text='신혼부부 전용 정책 (API 코드 없음 → 텍스트 파싱)'),
        ),
        migrations.AddField(
            model_name='policy',
            name='is_for_single_parent',
            field=models.BooleanField(default=False, help_text='한부모 전용 정책 (sbizCd: 0014004)'),
        ),
        migrations.AddField(
            model_name='policy',
            name='sbiz_cd',
            field=models.CharField(blank=True, help_text='API 원본 sbizCd (콤마 구분)', max_length=200),
        ),
    ]
