# Generated by Django 6.0.1 on 2026-01-20 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('policies', '0005_policy_is_for_disabled_policy_is_for_low_income_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='policy',
            name='lclsf_nm',
            field=models.CharField(blank=True, help_text='대분류 (일자리, 주거, 교육, 복지문화, 참여권리)', max_length=50),
        ),
        migrations.AddField(
            model_name='policy',
            name='mclsf_nm',
            field=models.CharField(blank=True, help_text='중분류 (원본 API mclsfNm)', max_length=50),
        ),
    ]
