# Generated by Django 5.2.11 on 2026-02-11 14:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('policies', '0007_rename_fields_to_english'),
    ]

    operations = [
        migrations.CreateModel(
            name='MapTheme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('theme_id', models.CharField(help_text='스마트 서울맵 테마 ID', max_length=50, unique=True)),
                ('name', models.CharField(help_text='테마 이름 (예: [동행]청년공간)', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='MapPOI',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='장소명', max_length=200)),
                ('latitude', models.FloatField(help_text='위도 (WGS84)')),
                ('longitude', models.FloatField(help_text='경도 (WGS84)')),
                ('address', models.CharField(blank=True, help_text='주소', max_length=500)),
                ('phone', models.CharField(blank=True, help_text='연락처', max_length=50)),
                ('detail_url', models.URLField(blank=True, help_text='상세 정보 URL')),
                ('original_data', models.JSONField(blank=True, default=dict, help_text='API 원본 데이터')),
                ('theme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pois', to='policies.maptheme')),
            ],
        ),
    ]
