# Generated by Django 5.2.11 on 2026-02-24 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('policies', '0008_maptheme_mappoi'),
    ]

    operations = [
        migrations.AddField(
            model_name='maptheme',
            name='metadata',
            field=models.JSONField(blank=True, default=dict, help_text='API 원본 테마 데이터'),
        ),
    ]
