# Generated by Django 5.2.11 on 2026-03-04 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('policies', '0009_maptheme_metadata'),
    ]

    operations = [
        migrations.AddField(
            model_name='policy',
            name='poster',
            field=models.ImageField(blank=True, help_text='정책 전용 포스터 이미지 (없으면 카테고리 기본 이미지 사용)', null=True, upload_to='policy_posters/'),
        ),
    ]
