# Generated by Django 5.2.10 on 2026-03-15 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('policies', '0010_add_poster_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='policy',
            name='detail_url',
            field=models.URLField(blank=True, help_text='상세 정보 URL'),
        ),
    ]
